allow binary data in OAuth1Session.request
In Python 2, binary data was handled just fine, because type bytes was
just a wrapper around str

    >>> data = bytes(1)
    >>> 'a' in data
    False

In Python 3, this gives an error

    >>> data = bytes(1)
    >>> 'a' in data
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    TypeError: 'str' does not support the buffer interface

Example client code: Python 3 port of
https://github.com/marekrei/smuploader